"""GUI-neutral chain editing model tests."""

from __future__ import annotations

import json
import sys
from dataclasses import replace

import pytest

from audiocli.capabilities import IOShape, get_capability, list_capabilities
from audiocli.chains import (
    CapabilityChain,
    ChainFormatError,
    ChainModel,
    load_chain,
    save_chain,
)


def test_chain_editing_operations_keep_stable_order_and_serializable_state():
    sys.modules.pop("audiocli.cli", None)
    chain = CapabilityChain(id="chain-1", name="Mastering")

    chain.add_node("builtin.filter.gain", {"db": "-3"}, node_id="gain-1")
    chain.add_node("builtin.filter.highpass", {"hz": 120}, node_id="hp-1")
    chain.move_node("hp-1", 0)
    chain.duplicate_node("gain-1", node_id="gain-2", index=1)
    chain.update_node_params("gain-2", {"db": 6})
    chain.set_node_enabled("gain-1", False)

    assert isinstance(chain, ChainModel)
    assert [node.id for node in chain.nodes] == ["hp-1", "gain-2", "gain-1"]
    assert chain.nodes[2].enabled is False
    assert chain.nodes[1].params == {"db": 6}
    assert "audiocli.cli" not in sys.modules

    view_model = chain.to_view_model()
    assert view_model["id"] == "chain-1"
    assert [node["position"] for node in view_model["nodes"]] == [0, 1, 2]
    assert [node["capability_id"] for node in view_model["nodes"]] == [
        "builtin.filter.highpass",
        "builtin.filter.gain",
        "builtin.filter.gain",
    ]
    assert view_model["nodes"][2]["enabled"] is False
    assert view_model["nodes"][1]["params"] == {"db": 6}
    assert view_model["nodes"][1]["capability"]["display_name"] == "Gain"
    assert view_model["validation_state"]["valid"] is True

    serialized = chain.to_dict()
    assert serialized == {
        "version": 1,
        "id": "chain-1",
        "name": "Mastering",
        "nodes": [
            {
                "id": "hp-1",
                "capability_id": "builtin.filter.highpass",
                "enabled": True,
                "params": {"hz": 120},
            },
            {
                "id": "gain-2",
                "capability_id": "builtin.filter.gain",
                "enabled": True,
                "params": {"db": 6},
            },
            {
                "id": "gain-1",
                "capability_id": "builtin.filter.gain",
                "enabled": False,
                "params": {"db": "-3"},
            },
        ],
    }
    json.dumps(serialized, allow_nan=False)

    removed = chain.delete_node("gain-2")
    assert removed.id == "gain-2"
    assert [node.id for node in chain.nodes] == ["hp-1", "gain-1"]


def test_chain_rejects_duplicate_node_ids_in_editing_operations():
    chain = CapabilityChain(id="chain-duplicates")
    first = chain.add_node("builtin.filter.gain", {"db": 1}, node_id="gain")

    with pytest.raises(ValueError, match="Duplicate chain node id 'gain'"):
        chain.add_node("builtin.filter.highpass", {"hz": 120}, node_id="gain")

    assert chain.nodes == [first]

    with pytest.raises(ValueError, match="Duplicate chain node id 'gain'"):
        chain.duplicate_node("gain", node_id="gain")

    with pytest.raises(ValueError, match="Duplicate chain node id 'gain'"):
        chain.duplicate_node("gain", new_node_id="gain")

    second = chain.add_node("builtin.filter.highpass", {"hz": 120}, node_id="highpass")
    with pytest.raises(ValueError, match="Duplicate chain node id 'highpass'"):
        chain.duplicate_node("gain", new_node_id="highpass")

    autogenerated = chain.duplicate_node("gain")

    assert [node.id for node in chain.nodes[:2]] == ["gain", autogenerated.id]
    assert autogenerated.id not in {first.id, second.id}


def test_disabled_nodes_remain_in_editor_but_are_skipped_by_validation_and_plan():
    chain = CapabilityChain(id="chain-disabled")
    chain.add_node("builtin.filter.gain", {"db": 2.5}, node_id="gain")
    chain.add_node(
        "missing.capability", {"bad": object()}, node_id="disabled-unknown", enabled=False
    )
    chain.add_node(
        "builtin.filter.highpass", {"hz": "not-a-number"}, node_id="disabled-invalid", enabled=False
    )

    validation = chain.validate()
    plan = chain.to_execution_plan()
    view_model = chain.to_view_model()

    assert validation.valid is True
    assert validation.errors == []
    assert [step.node_id for step in plan.steps] == ["gain"]
    assert view_model["node_count"] == 3
    assert view_model["enabled_node_count"] == 1
    assert [node["id"] for node in view_model["nodes"]] == [
        "gain",
        "disabled-unknown",
        "disabled-invalid",
    ]
    assert view_model["nodes"][1]["enabled"] is False
    assert view_model["nodes"][1]["capability"] is None
    assert view_model["nodes"][1]["validation_state"]["skipped"] is True


def test_chain_validation_reports_unknown_capability_bad_params_and_no_enabled_nodes():
    chain = CapabilityChain(id="bad-chain")
    chain.add_node("builtin.filter.gain", {}, node_id="gain-missing-db")
    chain.add_node("does.not.exist", {}, node_id="unknown")

    validation = chain.validate()

    assert validation.valid is False
    errors = {(error.node_id, error.code, error.parameter) for error in validation.errors}
    assert ("gain-missing-db", "missing_required", "db") in errors
    assert ("unknown", "unknown_capability", "") in errors
    assert validation.to_view_model()["valid"] is False

    disabled_only = CapabilityChain(id="disabled-only")
    disabled_only.add_node("builtin.filter.gain", {"db": 1}, node_id="gain", enabled=False)

    disabled_validation = disabled_only.validate()

    assert disabled_validation.valid is False
    assert [error.code for error in disabled_validation.errors] == ["no_enabled_nodes"]


def test_compatibility_validation_catches_incompatible_enabled_sequence_before_execution():
    audio_filter = get_capability("builtin.filter.highpass")
    metadata_shape = IOShape(
        kind="metadata",
        media_type="application/json",
        cardinality="single",
        description="Analysis metadata, not audio.",
    )
    analysis_capability = replace(
        audio_filter,
        id="test.analysis.metadata",
        type="analysis",
        display_name="Metadata Analysis",
        output_shape=metadata_shape,
        operation_name="metadata-analysis",
    )
    chain = CapabilityChain(
        id="incompatible",
        capability_catalog={
            analysis_capability.id: analysis_capability,
            audio_filter.id: audio_filter,
        },
    )
    chain.add_node(analysis_capability.id, node_id="analysis")
    chain.add_node(audio_filter.id, node_id="filter")

    validation = chain.validate()

    assert validation.valid is False
    assert len(validation.errors) == 1
    error = validation.errors[0]
    assert error.code == "incompatible_shapes"
    assert error.source_node_id == "analysis"
    assert error.node_id == "filter"
    assert "metadata" in error.message
    assert "audio_buffer" in error.message

    chain.set_node_enabled("analysis", False)
    assert [node.id for node in chain.nodes] == ["analysis", "filter"]
    assert chain.validate().valid is True
    assert [step.node_id for step in chain.to_execution_plan().steps] == ["filter"]


def test_chain_validation_allows_chunk_collection_into_filter_explicitly():
    chain = CapabilityChain(id="chunk-map")
    chain.add_node(
        "builtin.multi_output.chunk",
        {"seconds": 10.0, "pad": False},
        node_id="chunk",
    )
    chain.add_node("builtin.filter.gain", {"db": 0.0}, node_id="gain")

    validation = chain.validate()
    plan = chain.to_execution_plan()

    assert validation.valid is True
    assert validation.errors == []
    assert len(validation.collection_mappings) == 1
    mapping = validation.collection_mappings[0]
    assert mapping.source_node_id == "chunk"
    assert mapping.node_id == "gain"
    assert mapping.source_cardinality == "many"
    assert mapping.input_cardinality == "single"
    assert mapping.behavior == "map_each_file"
    assert validation.to_view_model()["collection_mappings"][0]["behavior"] == "map_each_file"
    assert [step.operation_name for step in plan.steps] == ["chunk", "gain"]


def test_chain_validation_rejects_invalid_chunk_seconds_before_plan():
    chain = CapabilityChain(id="bad-chunk")
    chain.add_node("builtin.multi_output.chunk", {"seconds": 0}, node_id="chunk")

    validation = chain.validate()

    assert validation.valid is False
    assert validation.errors[0].code == "below_minimum"
    assert validation.errors[0].parameter == "seconds"
    with pytest.raises(ValueError, match="below_minimum"):
        chain.to_execution_plan()


def test_chain_round_trips_from_serialization_ready_state():
    state = {
        "version": 1,
        "id": "chain-rt",
        "name": "Round Trip",
        "nodes": [
            {
                "id": "one",
                "capability_id": "builtin.filter.highpass",
                "enabled": True,
                "params": {"hz": 80.0},
            },
            {
                "id": "two",
                "capability_id": "builtin.filter.gain",
                "enabled": False,
                "params": {"db": -1.5},
            },
        ],
    }

    chain = CapabilityChain.from_dict(state)

    assert chain.id == "chain-rt"
    assert chain.name == "Round Trip"
    assert chain.to_dict() == state
    assert chain.to_view_model()["nodes"][0]["capability"]["operation_name"] == "highpass"


def test_chain_from_dict_rejects_duplicate_serialized_node_ids():
    state = {
        "version": 1,
        "id": "chain-duplicate-state",
        "name": "Duplicate State",
        "nodes": [
            {
                "id": "same",
                "capability_id": "builtin.filter.highpass",
                "enabled": True,
                "params": {"hz": 80.0},
            },
            {
                "id": "same",
                "capability_id": "builtin.filter.gain",
                "enabled": True,
                "params": {"db": -1.5},
            },
        ],
    }

    with pytest.raises(ValueError, match="Duplicate chain node id 'same'"):
        CapabilityChain.from_dict(state)


def test_native_chain_save_load_round_trip_preserves_metadata_and_node_policy(tmp_path):
    path = tmp_path / "Master Chain.aclichain"
    chain = CapabilityChain(
        id="chain-native",
        name="Native Chain",
        description="Reusable mastering chain",
        notes="Use gently",
        output_policy={"mode": "replace", "format": "wav"},
    )
    chain.add_node(
        "builtin.filter.highpass",
        {"hz": 75},
        node_id="hp",
        notes="Remove rumble",
        output_policy={"future": True},
    )
    chain.add_node("builtin.filter.gain", {"db": -2}, node_id="gain", enabled=False)

    saved_path = save_chain(chain, path)
    loaded = load_chain(saved_path)

    assert loaded.source_path == path
    assert loaded.chain_dir == tmp_path
    assert loaded.id == "chain-native"
    assert loaded.name == "Native Chain"
    assert loaded.description == "Reusable mastering chain"
    assert loaded.notes == "Use gently"
    assert loaded.output_policy == {"mode": "replace", "format": "wav"}
    assert [node.id for node in loaded.nodes] == ["hp", "gain"]
    assert [node.capability_id for node in loaded.nodes] == [
        "builtin.filter.highpass",
        "builtin.filter.gain",
    ]
    assert loaded.nodes[0].params == {"hz": 75}
    assert loaded.nodes[0].notes == "Remove rumble"
    assert loaded.nodes[0].output_policy == {"future": True}
    assert loaded.nodes[1].enabled is False

    native = json.loads(path.read_text())
    assert native["schema_version"] == 1
    assert native["kind"] == "audiocli.saved_chain"
    assert native["nodes"][0]["node_type"] == "capability"
    assert loaded.to_native_dict() == native


def test_native_chain_load_rejects_schema_errors(tmp_path):
    missing_schema = tmp_path / "missing.aclichain"
    missing_schema.write_text(json.dumps({"id": "bad", "name": "Bad", "nodes": []}))

    with pytest.raises(ChainFormatError) as missing_error:
        load_chain(missing_schema)

    assert missing_error.value.code == "missing_schema_version"

    bad_nodes = tmp_path / "bad-nodes.aclichain"
    bad_nodes.write_text(
        json.dumps(
            {
                "schema_version": 1,
                "kind": "audiocli.saved_chain",
                "id": "bad",
                "name": "Bad",
                "nodes": {"not": "a list"},
            }
        )
    )

    with pytest.raises(ChainFormatError) as schema_error:
        load_chain(bad_nodes)

    assert schema_error.value.code == "schema_error"


def test_native_chain_load_rejects_missing_or_invalid_node_type(tmp_path):
    base = {
        "schema_version": 1,
        "kind": "audiocli.saved_chain",
        "id": "bad-node-type",
        "name": "Bad Node Type",
        "nodes": [
            {
                "id": "gain",
                "node_type": "capability",
                "capability_id": "builtin.filter.gain",
                "enabled": True,
                "params": {"db": 1},
            }
        ],
    }

    missing_node_type = tmp_path / "missing-node-type.aclichain"
    missing_payload = json.loads(json.dumps(base))
    del missing_payload["nodes"][0]["node_type"]
    missing_node_type.write_text(json.dumps(missing_payload))

    with pytest.raises(ChainFormatError) as missing_error:
        load_chain(missing_node_type)

    assert missing_error.value.code == "schema_error"
    assert "node_type" in str(missing_error.value)

    invalid_node_type = tmp_path / "invalid-node-type.aclichain"
    invalid_payload = json.loads(json.dumps(base))
    invalid_payload["nodes"][0]["node_type"] = "macro"
    invalid_node_type.write_text(json.dumps(invalid_payload))

    with pytest.raises(ChainFormatError) as invalid_error:
        load_chain(invalid_node_type)

    assert invalid_error.value.code == "schema_error"
    assert "unsupported node_type" in str(invalid_error.value)


@pytest.mark.parametrize("schema_version", ["1", 1.9, True])
def test_native_chain_load_rejects_non_json_integer_schema_version(tmp_path, schema_version):
    path = tmp_path / f"bad-schema-{type(schema_version).__name__}.aclichain"
    path.write_text(
        json.dumps(
            {
                "schema_version": schema_version,
                "kind": "audiocli.saved_chain",
                "id": "bad-schema",
                "name": "Bad Schema",
                "nodes": [],
            }
        )
    )

    with pytest.raises(ChainFormatError) as error:
        load_chain(path)

    assert error.value.code == "schema_error"
    assert "JSON integer number" in str(error.value)


@pytest.mark.parametrize(
    ("field_path", "value", "message"),
    [
        (("notes",), ["not", "a", "string"], "field 'notes' must be a string"),
        (("nodes", 0, "enabled"), "false", "field 'enabled' must be a boolean"),
        (("nodes", 0, "params"), ["not", "an", "object"], "params must be an object"),
    ],
)
def test_native_chain_load_rejects_malformed_core_field_types(tmp_path, field_path, value, message):
    payload = {
        "schema_version": 1,
        "kind": "audiocli.saved_chain",
        "id": "strict-schema",
        "name": "Strict Schema",
        "nodes": [
            {
                "id": "gain",
                "node_type": "capability",
                "capability_id": "builtin.filter.gain",
                "enabled": True,
                "params": {"db": 1},
            }
        ],
    }
    target = payload
    for key in field_path[:-1]:
        target = target[key]
    target[field_path[-1]] = value
    path = tmp_path / f"bad-core-{len(field_path)}.aclichain"
    path.write_text(json.dumps(payload))

    with pytest.raises(ChainFormatError) as error:
        load_chain(path)

    assert error.value.code == "schema_error"
    assert message in str(error.value)


def test_invalid_native_chain_kind_is_excluded_from_macro_discovery(tmp_path):
    valid = CapabilityChain(id="valid", name="Valid")
    invalid = CapabilityChain(id="invalid", name="Invalid")
    valid_path = save_chain(valid, tmp_path / "valid.aclichain")
    invalid_path = save_chain(invalid, tmp_path / "invalid.aclichain")
    invalid_payload = json.loads(invalid_path.read_text())
    invalid_payload["kind"] = "not.audiocli.saved_chain"
    invalid_path.write_text(json.dumps(invalid_payload))

    capabilities = list_capabilities(chain_dir=tmp_path)
    macro_chain_ids = {
        capability.defaults.get("chain_id")
        for capability in capabilities
        if capability.type == "saved_chain_macro"
    }

    assert valid_path.exists()
    assert "valid" in macro_chain_ids
    assert "invalid" not in macro_chain_ids


def test_direct_saved_chain_recursion_is_rejected(tmp_path):
    from audiocli.capabilities import list_capabilities

    path = tmp_path / "self.aclichain"
    chain = CapabilityChain(id="self", name="Self", source_path=path, chain_dir=tmp_path)
    save_chain(chain, path)
    catalog = {cap.id: cap for cap in list_capabilities(chain_dir=tmp_path)}
    macro = next(cap for cap in catalog.values() if cap.type == "saved_chain_macro")
    chain.add_node(macro.id, {"path": str(path), "chain_id": "self"}, node_id="macro")
    save_chain(chain, path)

    loaded = load_chain(path, capability_catalog=catalog)
    validation = loaded.validate()

    assert validation.valid is False
    assert validation.errors[0].code == "recursive_chain"
    assert "Recursive saved-chain reference rejected" in validation.errors[0].message


def test_indirect_saved_chain_recursion_is_rejected(tmp_path):
    from audiocli.capabilities import list_capabilities

    path_a = tmp_path / "a.aclichain"
    path_b = tmp_path / "b.aclichain"
    chain_a = CapabilityChain(id="a", name="A", source_path=path_a, chain_dir=tmp_path)
    chain_b = CapabilityChain(id="b", name="B", source_path=path_b, chain_dir=tmp_path)
    save_chain(chain_a, path_a)
    save_chain(chain_b, path_b)

    catalog = {cap.id: cap for cap in list_capabilities(chain_dir=tmp_path)}
    macro_a = next(cap for cap in catalog.values() if cap.defaults.get("chain_id") == "a")
    macro_b = next(cap for cap in catalog.values() if cap.defaults.get("chain_id") == "b")
    chain_a.add_node(macro_b.id, {"path": str(path_b), "chain_id": "b"}, node_id="to-b")
    chain_b.add_node(macro_a.id, {"path": str(path_a), "chain_id": "a"}, node_id="to-a")
    save_chain(chain_a, path_a)
    save_chain(chain_b, path_b)

    loaded = load_chain(path_a, capability_catalog=catalog)
    validation = loaded.validate()

    assert validation.valid is False
    assert [error.code for error in validation.errors] == ["recursive_chain"]
    assert str(path_b) in validation.errors[0].message
    assert str(path_a) in validation.errors[0].message


def test_nested_relative_saved_chain_backreference_is_rejected(tmp_path):
    subdir = tmp_path / "sub"
    path_a = tmp_path / "a.aclichain"
    path_b = subdir / "b.aclichain"
    chain_a = CapabilityChain(id="a", name="A", source_path=path_a, chain_dir=tmp_path)
    chain_b = CapabilityChain(id="b", name="B", source_path=path_b, chain_dir=subdir)
    save_chain(chain_a, path_a)
    save_chain(chain_b, path_b)

    catalog = {
        cap.id: cap
        for cap in [*list_capabilities(chain_dir=tmp_path), *list_capabilities(chain_dir=subdir)]
    }
    macro_a = next(cap for cap in catalog.values() if cap.defaults.get("chain_id") == "a")
    macro_b = next(cap for cap in catalog.values() if cap.defaults.get("chain_id") == "b")
    chain_a.add_node(macro_b.id, {"path": "sub/b.aclichain", "chain_id": "b"}, node_id="to-b")
    chain_b.add_node(macro_a.id, {"path": "../a.aclichain", "chain_id": "a"}, node_id="to-a")
    save_chain(chain_a, path_a)
    save_chain(chain_b, path_b)

    loaded = load_chain(path_a, capability_catalog=catalog)
    validation = loaded.validate()

    assert validation.valid is False
    assert [error.code for error in validation.errors] == ["recursive_chain"]
    assert str(path_b) in validation.errors[0].message
    assert str(path_a) in validation.errors[0].message


def test_nested_default_param_saved_chain_backreference_is_rejected(tmp_path):
    subdir = tmp_path / "sub"
    path_a = tmp_path / "a.aclichain"
    path_b = subdir / "b.aclichain"
    chain_a = CapabilityChain(id="a", name="A", source_path=path_a, chain_dir=tmp_path)
    chain_b = CapabilityChain(id="b", name="B", source_path=path_b, chain_dir=subdir)
    save_chain(chain_a, path_a)
    save_chain(chain_b, path_b)

    catalog = {
        cap.id: cap
        for cap in [*list_capabilities(chain_dir=tmp_path), *list_capabilities(chain_dir=subdir)]
    }
    macro_a = next(cap for cap in catalog.values() if cap.defaults.get("chain_id") == "a")
    macro_b = next(cap for cap in catalog.values() if cap.defaults.get("chain_id") == "b")
    chain_a.add_node(macro_b.id, {}, node_id="to-b")
    chain_b.add_node(macro_a.id, {}, node_id="to-a")
    save_chain(chain_a, path_a)
    save_chain(chain_b, path_b)

    loaded = load_chain(path_a, capability_catalog=catalog)
    validation = loaded.validate()

    assert validation.valid is False
    assert [error.code for error in validation.errors] == ["recursive_chain"]
    assert str(path_b) in validation.errors[0].message
    assert str(path_a) in validation.errors[0].message


def test_reachable_nested_saved_chain_cycle_not_involving_root_is_rejected(tmp_path):
    path_a = tmp_path / "a.aclichain"
    path_b = tmp_path / "b.aclichain"
    path_c = tmp_path / "c.aclichain"
    chain_a = CapabilityChain(id="a", name="A", source_path=path_a, chain_dir=tmp_path)
    chain_b = CapabilityChain(id="b", name="B", source_path=path_b, chain_dir=tmp_path)
    chain_c = CapabilityChain(id="c", name="C", source_path=path_c, chain_dir=tmp_path)
    save_chain(chain_a, path_a)
    save_chain(chain_b, path_b)
    save_chain(chain_c, path_c)

    catalog = {cap.id: cap for cap in list_capabilities(chain_dir=tmp_path)}
    macro_b = next(cap for cap in catalog.values() if cap.defaults.get("chain_id") == "b")
    macro_c = next(cap for cap in catalog.values() if cap.defaults.get("chain_id") == "c")
    chain_a.add_node(macro_b.id, {"path": str(path_b), "chain_id": "b"}, node_id="to-b")
    chain_b.add_node(macro_c.id, {"path": str(path_c), "chain_id": "c"}, node_id="to-c")
    chain_c.add_node(macro_b.id, {"path": str(path_b), "chain_id": "b"}, node_id="back-to-b")
    save_chain(chain_a, path_a)
    save_chain(chain_b, path_b)
    save_chain(chain_c, path_c)

    loaded = load_chain(path_a, capability_catalog=catalog)
    validation = loaded.validate()

    assert validation.valid is False
    assert [error.code for error in validation.errors] == ["recursive_chain"]
    assert str(path_b) in validation.errors[0].message
    assert str(path_c) in validation.errors[0].message
    assert str(path_a) not in validation.errors[0].message
